# Generated by Django 4.1.7 on 2023-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
    ]
