# Generated by Django 4.1.7 on 2023-02-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('cars', '0002_alter_car_year'),
        ('services', '0002_service_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carro', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Serviços', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
