# Generated by Django 4.1.7 on 2023-02-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_car_alter_service_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='client',
            new_name='client_id',
        ),
    ]
