# Generated by Django 4.1.7 on 2023-02-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0004_rename_client_service_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='clients.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='ref_code',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
